after_success:
- ./mvnw jacoco:report coveralls:report
- '[[ ${TRAVIS_PULL_REQUEST} == ''false'' ]] && [[ ${TRAVIS_TAG} == '''' ]] && ./mvnw
  deploy -DreposityId=sonatype-nexus-snapshots -DskipTests --settings deploy-settings.xml'
- '[[ ${TRAVIS_PULL_REQUEST} == ''false'' ]] && [[ ${TRAVIS_TAG} != '''' ]] && ./mvnw
  deploy -DreposityId=sonatype-nexus-staging -DskipTests -Drevision=${TRAVIS_TAG}
  --settings deploy-settings.xml'
before_cache:
- cp /tmp/classpathFile $HOME/CACHE/classpathFile
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
- if [[ -n "$DECRYPT_KEYPHRASE" ]]; then openssl aes-256-cbc -d -pass "env:DECRYPT_KEYPHRASE"
  -in .gnupg.tar.enc | tar xv; fi
- if [[ ${TRAVIS_TAG} != "" ]]; then ./mvnw versions:set -DnewVersion="${TRAVIS_TAG}";
  fi
- nvm install ${TRAVIS_NODE_VERSION} && nvm use ${TRAVIS_NODE_VERSION}
before_script:
- if [ "$TRAVIS_OS_NAME" == "osx" ];    then sed -i '' 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    else sed -i 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    fi
- if [[ -e $HOME/CACHE/classpathFile ]]; then cp $HOME/CACHE/classpathFile /tmp/;
  fi
cache:
  directories:
  - $HOME/.m2
  - $HOME/.npm
env:
- TRAVIS_NODE_VERSION="lts/*"
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- ./mvnw verify ${TRAVIS_TAG:+-Drevision=${TRAVIS_TAG}}
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
